[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[cart]
cart-dev.ljnag.space

[mysql]
mysql-dev.ljnag.space

[shipping]
shipping-dev.ljnag.space

[payment]
payment-dev.ljnag.space

[rabbitmq]
rabbitmq-dev.ljnag.space

[frontend]
roboshop-dev.ljnag.space


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
