- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup.yaml    

- name: syatemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

# - name: Replace socket and protocol with http
#   ansible.builtin.replace:
#     path: /app/payment.ini
#     regexp: 'socket\s*=\s*0\.0\.0\.0:8080\s*\nprotocol\s*=\s*http'
#     replace: 'http = 0.0.0.0:8080'

- name: restart payment
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes