- name: Installl mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: install python dependencies to connect with aws
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
  - botocore
  - boto3     

- name: Start and enable mysqld
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"