- name: restart "{{ component }}" 
  ansible.builtin.service:
    name: "{{ component }}" 
    state: restarted
    enabled: yes     

- name: restart payment
  ansible.builtin.service:
    name: payment
    state: restarted    